services:
  api-server:
    volumes:
      - /Users/luisgonzalez/Documents/code/etl pipeline/github_etl:/usr/local/airflow/project
    environment:
      PYTHONPATH: /usr/local/airflow/project
    networks: [etl-shared]

  dag-processor:
    volumes:
      - /Users/luisgonzalez/Documents/code/etl pipeline/github_etl:/usr/local/airflow/project
    environment:
      PYTHONPATH: /usr/local/airflow/project
    networks: [etl-shared]

  scheduler:
    volumes:
      - /Users/luisgonzalez/Documents/code/etl pipeline/github_etl:/usr/local/airflow/project
    environment:
      PYTHONPATH: /usr/local/airflow/project
    networks: [etl-shared]

  triggerer:
    volumes:
      - /Users/luisgonzalez/Documents/code/etl pipeline/github_etl:/usr/local/airflow/project
    environment:
      PYTHONPATH: /usr/local/airflow/project
    networks: [etl-shared]


networks:
  etl-shared:
    external: true